AWSTemplateFormatVersion: "2010-09-09"
Description: Team11 DynamoDB Table for Mesh Metadata

Parameters:
  EnvType:
    Type: String
    Default: prod

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "team11-dynamodb-table-${EnvType}"
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  MeshMetaTableName:
    Value: !Ref DynamoDBTable
