AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository for Backend

Parameters:
  RepoName:
    Type: String
    Default: team11-backend-repo

Resources:
  BackendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepoName
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Value: !GetAtt BackendRepository.RepositoryUri
  RepositoryName:
    Value: !Ref BackendRepository
