AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda Container Function

Parameters:
  EcrRepoUri:
    Type: String
  ImageTag:
    Type: String
  EnvType:
    Type: String
    Default: prod
  FrontendUrl:
    Type: String
    Description: Frontend URL for CORS configuration
  DynamoDBTableName:
    Type: String
    Description: DynamoDB table name for mesh metadata
  S3BucketName:
    Type: String
    Description: S3 bucket name for data source

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SSMReadAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ssm:GetParameter
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/team11/*"
        - PolicyName: DynamoDBReadAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}"
        - PolicyName: S3PresignedUrlAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"
        - PolicyName: BedrockInvokeAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: "arn:aws:bedrock:*::foundation-model/amazon.nova-micro-v1:0"
        - PolicyName: StepFunctionsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                  - states:DescribeExecution
                Resource:
                  - Fn::ImportValue: Team11AIEnginePipelineArn

  BackendFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "team11-backend-${EnvType}"
      PackageType: Image
      Code:
        ImageUri: !Sub "${EcrRepoUri}:${ImageTag}"
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 512
      Architectures: [x86_64]
      Environment:
        Variables:
          ENV_TYPE: !Ref EnvType
          FRONTEND_URL: "{{resolve:ssm:/team11/prod/frontend-url}}"
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
          S3_BUCKET_NAME: !Ref S3BucketName
          STATE_MACHINE_ARN:
            Fn::ImportValue: Team11AIEnginePipelineArn

  FunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref BackendFunction
      AuthType: NONE
      Cors:
        AllowOrigins:
          - !Ref FrontendUrl
        AllowMethods: ["*"]
        AllowHeaders: ["*"]

  FunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BackendFunction
      Principal: "*"
      Action: lambda:InvokeFunctionUrl
      FunctionUrlAuthType: NONE

  FunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BackendFunction
      Principal: "*"
      Action: lambda:InvokeFunction

Outputs:
  ApiUrl:
    Value: !GetAtt FunctionUrl.FunctionUrl
