AWSTemplateFormatVersion: "2010-09-09"
Description: Team11 Backend Parent Stack

Parameters:
  EnvType:
    Type: String
    Default: prod
  ImageTag:
    Type: String
  FrontendUrl:
    Type: String
    Description: Frontend URL for CORS configuration
  S3BucketName:
    Type: String
    Description: S3 bucket name for data source

Resources:
  # ------------------------------------------------------------
  # ECR
  # ------------------------------------------------------------
  ECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecr.yml
      Parameters:
        RepoName: !Sub "team11-backend-repo-${EnvType}"

  # ------------------------------------------------------------
  # Lambda
  # ------------------------------------------------------------
  Lambda:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ECR
      - DynamoDB
    Properties:
      TemplateURL: ./lambda.yml
      Parameters:
        EcrRepoUri: !GetAtt ECR.Outputs.RepositoryUri
        ImageTag: !Ref ImageTag
        EnvType: !Ref EnvType
        FrontendUrl: !Ref FrontendUrl
        DynamoDBTableName: !GetAtt DynamoDB.Outputs.MeshMetaTableName
        S3BucketName: !Ref S3BucketName

  # ------------------------------------------------------------
  # DynamoDB (Mesh Metadata)
  # ------------------------------------------------------------
  DynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./dynamodb.yml
      Parameters:
        EnvType: !Ref EnvType

  # ------------------------------------------------------------
  # Data Writer Lambda
  # ------------------------------------------------------------
  DataWriterLambda:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDB
    Properties:
      TemplateURL: ./data-writer-lambda.yml
      Parameters:
        EnvType: !Ref EnvType
        DynamoDBTableName: !GetAtt DynamoDB.Outputs.MeshMetaTableName

Outputs:
  ApiEndpoint:
    Value: !GetAtt Lambda.Outputs.ApiUrl
  MeshMetaTableName:
    Value: !GetAtt DynamoDB.Outputs.MeshMetaTableName
  DataWriterFunctionArn:
    Value: !GetAtt DataWriterLambda.Outputs.DataWriterFunctionArn
