AWSTemplateFormatVersion: '2010-09-09'
Description: Team11 Backend Parent Stack

Parameters:
  EnvType:
    Type: String
    Default: prod
  ImageTag:
    Type: String

Resources:
  # ------------------------------------------------------------
  # ECR
  # ------------------------------------------------------------
  ECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecr.yml
      Parameters:
        RepoName: !Sub "team11-backend-repo-${EnvType}"

#   # ------------------------------------------------------------
#   # Lambda
#   # ------------------------------------------------------------
#   Lambda:
#     Type: AWS::CloudFormation::Stack
#     DependsOn: ECRStack
#     Properties:
#       TemplateURL: ./lambda.yml
#       Parameters:
#         EcrRepoUri: !GetAtt ECRStack.Outputs.RepositoryUri
#         ImageTag: !Ref ImageTag
#         EnvType: !Ref EnvType

# Outputs:
#   ApiEndpoint:
#     Value: !GetAtt LambdaStack.Outputs.ApiUrl
